version: '3.4'

volumes:
  identityapi:

networks:
  appnetwork:
    driver: bridge

services:
  client:
    image: ${DOCKER_REGISTRY-}client
    build:
      context: .
      dockerfile: Client.Dockerfile
    ports:
      - "8080:80"
  
  identityapi:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: IdentityApi.DockerFile
    depends_on:
      - identityapidatabase
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ScoreApiUrl=http://scoreapi:80/api/
      - ConnectionStrings__AppConnection=Host=identityapidatabase;Port=5432;Database=identityapidatabase;Username=postgres;Password=postgrespw;Pooling=true
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=9873
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "5521:443"
      - "5522:80"
    networks:
      - appnetwork
      
      
  scoreapi:
    image: ${DOCKER_REGISTRY-}scoreapi
    build:
      context: .
      dockerfile: ScoreApi.DockerFile
    depends_on:
      - scoreapidatabase
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AppConnection=Host=scoreapidatabase;Port=5432;Database=scoreapidatabase;Username=postgres;Password=postgrespw;Pooling=true
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=9873
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "5523:443"
      - "5524:80"
    networks:
      - appnetwork
  financeapi:
    image: ${DOCKER_REGISTRY-}financeapi
    build:
      context: .
      dockerfile: FinanceApi.DockerFile
    depends_on:
      - financeapidatabase
    environment:
      - ScoreApiUrl= http://scoreapi:80/api/
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AppConnection=Host=financeapidatabase;Port=5432;Database=financeapidatabase;Username=postgres;Password=postgrespw;Pooling=true
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=9873
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "5525:443"
      - "5526:80"
    networks:
      - appnetwork
  
  identityapidatabase:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - "5527:5432"
    volumes:
      - identityapi:/var/lib/postgresql
    networks:
      - appnetwork
    restart:
      always
    
  scoreapidatabase:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - "5528:5432"
    volumes:
      - identityapi:/var/lib/postgresql
    networks:
      - appnetwork
    restart:
      always
    
  financeapidatabase:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - "5529:5432"
    volumes:
      - identityapi:/var/lib/postgresql
    networks:
      - appnetwork
    restart:
      always