version: '3.4'

volumes:
  identityapi:

networks:
  appnetwork:
    driver: bridge

services:
  client:
    image: ${DOCKER_REGISTRY-}client
    build:
      context: .
      dockerfile: Client.Dockerfile
    ports:
      - "8080:80"
  
  identityapi:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: IdentityApi.DockerFile
    depends_on:
      - authenticationapidatabase
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AppConnection=Host=authenticationapidatabase;Port=5432;Database=authenticationapidatabase;Username=postgres;Password=postgrespw;Pooling=true
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=9873
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "5521:443"
      - "5522:80"
    networks:
      - appnetwork
  
  authenticationapidatabase:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - "5523:5432"
    volumes:
      - identityapi:/var/lib/postgresql
    networks:
      - appnetwork
    restart:
      always